import type { FoodItem } from "./types";

export const FOOD_DATABASE: FoodItem[] = [
  // ─── Raw Foods (per 100g) ──────────────────────────────────────────────────
  {
    id: "chicken_breast",
    nameEn: "Chicken Breast",
    nameAr: "صدر دجاج",
    type: "raw",
    caloriesPer: 165,
    proteinPer: 31,
    carbsPer: 0,
    fatPer: 3.6,
    servingLabel: "per 100g",
  },
  {
    id: "oats",
    nameEn: "Oats",
    nameAr: "شوفان",
    type: "raw",
    caloriesPer: 389,
    proteinPer: 17,
    carbsPer: 66,
    fatPer: 7,
    servingLabel: "per 100g",
  },
  {
    id: "white_rice",
    nameEn: "White Rice (cooked)",
    nameAr: "أرز أبيض (مطبوخ)",
    type: "raw",
    caloriesPer: 130,
    proteinPer: 2.7,
    carbsPer: 28,
    fatPer: 0.3,
    servingLabel: "per 100g",
  },
  {
    id: "eggs",
    nameEn: "Whole Egg",
    nameAr: "بيضة كاملة",
    type: "raw",
    caloriesPer: 155,
    proteinPer: 13,
    carbsPer: 1.1,
    fatPer: 11,
    servingLabel: "per 100g",
  },
  {
    id: "tuna_canned",
    nameEn: "Canned Tuna",
    nameAr: "تونة معلبة",
    type: "raw",
    caloriesPer: 116,
    proteinPer: 26,
    carbsPer: 0,
    fatPer: 1,
    servingLabel: "per 100g",
  },
  {
    id: "sweet_potato",
    nameEn: "Sweet Potato",
    nameAr: "بطاطا حلوة",
    type: "raw",
    caloriesPer: 86,
    proteinPer: 1.6,
    carbsPer: 20,
    fatPer: 0.1,
    servingLabel: "per 100g",
  },
  {
    id: "salmon",
    nameEn: "Salmon",
    nameAr: "سلمون",
    type: "raw",
    caloriesPer: 208,
    proteinPer: 20,
    carbsPer: 0,
    fatPer: 13,
    servingLabel: "per 100g",
  },
  {
    id: "greek_yogurt",
    nameEn: "Greek Yogurt",
    nameAr: "زبادي يوناني",
    type: "raw",
    caloriesPer: 59,
    proteinPer: 10,
    carbsPer: 3.6,
    fatPer: 0.4,
    servingLabel: "per 100g",
  },
  {
    id: "banana",
    nameEn: "Banana",
    nameAr: "موز",
    type: "raw",
    caloriesPer: 89,
    proteinPer: 1.1,
    carbsPer: 23,
    fatPer: 0.3,
    servingLabel: "per 100g",
  },
  {
    id: "almonds",
    nameEn: "Almonds",
    nameAr: "لوز",
    type: "raw",
    caloriesPer: 579,
    proteinPer: 21,
    carbsPer: 22,
    fatPer: 50,
    servingLabel: "per 100g",
  },
  // ─── Packaged Products (per unit/pack) ────────────────────────────────────
  {
    id: "hohos",
    nameEn: "Hohos (Cake)",
    nameAr: "هوهوز كيك",
    type: "packaged",
    caloriesPer: 120,
    proteinPer: 1.5,
    carbsPer: 20,
    fatPer: 4.5,
    servingLabel: "per pack",
  },
  {
    id: "mcvities",
    nameEn: "McVitie's Digestive Biscuits",
    nameAr: "بسكويت ماك فيتيز ديجستيف",
    type: "packaged",
    caloriesPer: 71,
    proteinPer: 1,
    carbsPer: 10,
    fatPer: 3,
    servingLabel: "per biscuit",
  },
  {
    id: "molto",
    nameEn: "Molto Croissant",
    nameAr: "مولتو كرواسون",
    type: "packaged",
    caloriesPer: 310,
    proteinPer: 5,
    carbsPer: 38,
    fatPer: 16,
    servingLabel: "per pack",
  },
  {
    id: "kinder_bueno",
    nameEn: "Kinder Bueno",
    nameAr: "كيندر بوينو",
    type: "packaged",
    caloriesPer: 245,
    proteinPer: 4.5,
    carbsPer: 25,
    fatPer: 14,
    servingLabel: "per bar",
  },
  {
    id: "twix",
    nameEn: "Twix Bar",
    nameAr: "تويكس",
    type: "packaged",
    caloriesPer: 286,
    proteinPer: 3,
    carbsPer: 38,
    fatPer: 14,
    servingLabel: "per bar",
  },
  {
    id: "lays_chips",
    nameEn: "Lay's Classic Chips",
    nameAr: "ليز كلاسيك",
    type: "packaged",
    caloriesPer: 155,
    proteinPer: 2,
    carbsPer: 15,
    fatPer: 10,
    servingLabel: "per bag (28g)",
  },
  {
    id: "protein_bar",
    nameEn: "Quest Protein Bar",
    nameAr: "كويست بروتين بار",
    type: "packaged",
    caloriesPer: 190,
    proteinPer: 21,
    carbsPer: 22,
    fatPer: 8,
    servingLabel: "per bar",
  },
];

export const ACTIVITY_MULTIPLIERS: Record<string, number> = {
  sedentary: 1.2,
  light: 1.375,
  moderate: 1.55,
  very_active: 1.725,
  extra_active: 1.9,
};

export const GOAL_ADJUSTMENTS: Record<string, { min: number; max: number }> = {
  bulk: { min: 300, max: 500 },
  cut: { min: -500, max: -300 },
  maintain: { min: 0, max: 0 },
};
